# Generated by Django 3.0.1 on 2020-09-03 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_post', models.TextField(max_length=140)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tweet_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
